### ISSUE TITLE
iOS - How to send http request when the app is terminated through silent push notifications?

### ISSUE THREAD

**Issue by luzushka** [pushy-me/pushy-react-native#18]
Hi,

I've read various posts or answers to questions online that told it's possible to "wake up" an app and make it perform a background task using a silent push notification.

I am following the guide from the docs + sending a silent push notification to the device through postman and the response is 200 Ok, but the listener doesn't get called when the app is closed (press home button twice, swipe up kind of closed).

Is this the expected behaviour? If so, how did WhatsApp implement message received receipts for example, or some apps preload data?

**Comment by pushy-me** [comment]
Hi @luzushka,
I'd be glad to provide insight.

Unfortunately this is expected behavior on iOS. Indeed the case with silent notifications (`content_available: true`) is that they will not wake up your app to execute code if the user swiped it away from recent apps:
https://stackoverflow.com/a/21227815/1123355

If you send the "notification" object with your silent notifications, at least a notification will be displayed to the user. Your listener will only be executed if the user interacts with the notification.
