### ISSUE TITLE
PushyModule.h Not Found

### ISSUE THREAD

**Issue by dmydry** [pushy-me/pushy-react-native#20]
Hello guys! I decided to reopen this issue since we really want to use your services with our project.

We have an ejected expo project. Already installed different native SDKs like `Intercom`, `FBSDK`, `react-native-idfa` etc and there were no issues with linking.

There are related issues but they are closed without any solutions.
https://github.com/pushy-me/pushy-react-native/issues/13
https://github.com/pushy-me/pushy-react-native/issues/19

@pushy-me Please help us to investigate this issue.

**Comment by pushy-me** [comment]
Hi @dmydry,
Apologies for the delayed response as we continued to investigate this issue.

We have spent several hours trying to get the Pushy React Native SDK working in Expo / ExpoKit and the conclusion we came to is that we  currently cannot support Expo apps (detached or not) because Headless JS tasks are not yet supported in ExpoKit and are currently broken:
https://forums.expo.io/t/appregistry-registerheadlesstask/15425

We were not able to find a solution to wake your app's JS code when the MainActivity is not running, in order to receive the notification and execute desirable JS code to handle it.

Therefore, until Expo adds support for headless JS (which means adding support `getReactNativeHost()` in `HeadlessJsTaskService`) we cannot support ExpoKit RN projects.

I apologize but at this time we can only support pure React Native projects and not ExpoKit due to this broken upstream functionality.

**Comment by dmydry** [comment]
@pushy-me thanks for the explanation!

**Comment by trajano** [comment]
I'm researching the use of @pushy-me  to handle the push notifications for our app since we plan to deploy to China.  However, we're using Expo right now is this bug still an issue?

**Comment by pushy-me** [comment]
Hi @trajano,
Yes, unfortunately, it is indeed still an upstream issue, as Expo still does not yet support Headless JS. We apologize for this inconvenience.
