### ISSUE TITLE
Pushy keeps charging me multiple times for the same device, if the device is reinstalled. 

### ISSUE THREAD

**Issue by tarikchakur** [pushy-me/pushy-react-native#21]
Hi. 
We are currently using Pushy in a react-native project, we've followed your documentation. and the service is well integrated in our app, except for the `Pricing part`, we've noticed [in the dahsboard](https://dashboard.pushy.me/)  that every time we reinstall the app the `TOTAL DEVICES` and the `ACTIVE DEVICES` indicators are incremented. Thus getting charged multiple times for a single device .
Note we've granted Pushy the storage permission just like you've instructed in the documentation. 

We're using: react-native@ 0.59.9 and pushy-react-native@1.0.8

**Issue:** How to prevent getting charged multiple times for the same device, if the device re-installs the app ? 

Thanks in advance. 

Here's our AndroidManifest.xml
```
<manifest 
   xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:tools="http://schemas.android.com/tools"
   package="xx.xx.xxxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <!-- Pushy Permissions -->
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
        android:name=".MainApplication"
        tools:node="replace"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="false"
        android:theme="@style/AppTheme">

        <activity 
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustPan"
            android:screenOrientation="portrait" />

        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <!-- Pushy Declarations -->

        <!-- Pushy Notification Receiver -->
        <!-- Do not modify - internal BroadcastReceiver that forwards notifications to the internal notification service-->
        <receiver android:name="me.pushy.sdk.react.receivers.PushReceiver" android:exported="false">
            <intent-filter>
                <!-- Do not modify this -->
                <action android:name="pushy.me" />
            </intent-filter>
        </receiver>

        <!-- Pushy Update Receiver -->
        <!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
        <receiver android:name="me.pushy.sdk.receivers.PushyUpdateReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>

        <!-- Pushy Boot Receiver -->
        <!-- Do not modify - internal BroadcastReceiver that restarts the listener service -->
        <receiver android:name="me.pushy.sdk.receivers.PushyBootReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

        <!-- Pushy Socket Service -->
        <!-- Do not modify - internal service -->
        <service android:name="me.pushy.sdk.services.PushySocketService"/>

        <!-- Pushy Job Service (added in Pushy SDK 1.0.35) -->
        <!-- Do not modify - internal service -->
        <service android:name="me.pushy.sdk.services.PushyJobService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true" />

    </application>

</manifest>
```

**Comment by pushy-me** [comment]
Hi @tarikchakur,
I'll be glad to assist.

Your device is getting assigned a new Pushy device token every time you reinstall because your app hasn't been granted the `WRITE_EXTERNAL_STORAGE` permission when calling `Pushy.register()`.

Please use this code sample to ensure that the user granted the `WRITE_EXTERNAL_STORAGE` permission before calling `Pushy.register()`, by removing your existing `Pushy.register()` invocation and using this code instead:

```
// Android-specific code
if (Platform.OS === 'android') {
    // Check whether the user has granted the app the WRITE_EXTERNAL_STORAGE permission
    PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE).then((granted) => {
        if (!granted) {
            // Request the WRITE_EXTERNAL_STORAGE permission so that the Pushy SDK will be able to persist the device token in the external storage
            PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE).then((result) => {
                // User denied permission?
                if (result !== PermissionsAndroid.RESULTS.GRANTED) {
                    // Possibly ask the user to grant the permission again, but don't continue to register the device
                }
                else {
                    // User granted the permission
                    // Register the device for push notifications
                    Pushy.register().then(async (deviceToken) => {
                        // Display an alert with device token
                        alert('Pushy device token: ' + deviceToken);

                        // Send the token to your backend server via an HTTP GET request
                        //await fetch('https://your.api.hostname/register/device?token=' + deviceToken);

                        // Succeeded, optionally do something to alert the user
                    }).catch((err) => {
                        // Handle registration errors
                        console.error(err);
                    }); 
                }
            });
        }
    });
}
```

**Note:** Please add `import {PermissionsAndroid} from 'react-native';` to the top of the file.

**Comment by hasis** [comment]
Is there any way to work around this without requiring `WRITE_EXTERNAL_STORAGE` for Android? This is a fairly heavy handed permission request and I'm afraid it will deter users from opting into Push Notifications, which can have a serious business impact.

**Comment by pushy-me** [comment]
Hi @hasis,
This is a great question.

Indeed the `WRITE_EXTERNAL_STORAGE` permission is optional for our SDK integration, but not requesting this permission means you may be charged numerous times for multiple installations of your app on the same device.

Unfortunately, our SDK has no way to identify / track the device except to write to the external storage, because internal storage gets wiped on app uninstall, and the Android Device ID is not unique enough to serve a reliable identifier.

However, if you are able to identify your users (e.g. via login mechanism in your app), you can store the user's Pushy device credentials (token & auth key) in your backend database, and when that same user reinstalls your app and logs in, you may reassign the device its Pushy credentials and this will prevent a new device token from being assigned to the device when calling `Pushy.register()`.

1) You can retrieve the Pushy device credentials using `Pushy.getDeviceCredentials(getApplicationContext())`, and store these in your backend after calling `Pushy.register()`. 

2) You can then re-set the same Pushy device credentials after users log into your app using the following code, after fetching these from your backend server as `token` and `authKey`:

```
Pushy.setDeviceCredentials(new PushyDeviceCredentials(String token, String authKey), getApplicationContext());
```

Please let me know if this makes sense.

**Comment by leeyuejia** [comment]
Hi I am integrating pushy into both android and ios. I am a starter for ios development. For the issue of charging multiple times for same device, I want to clarify that the work around is as follow : 
(for android) 
- After calling` Pushy.register()`, use `Pushy.getDeviceCredentials(getApplicationContext())` to store `token` and `authkey` in backend. 
- If user reinstall application, before it calls `Pushy.register()`, use `Pushy.setDeviceCredentials(new PushyDeviceCredentials(String token, String authKey), getApplicationContext());` and then call `Pushy.register()`
- This would register this device with the same token and authkey hence preventing multiple token tied to a single device. 

(ios) 
My question is how about iOS? How does it looked like in code level with react native? 

Thanks for your support.

**Comment by pushy** [comment]
Hi @leeyuejia,
Thanks for your inquiry. We'd be glad to assist.

The above suggested usage of `Pushy.getDeviceCredentials()` and `Pushy.setDeviceCredentials()` is outdated. The Pushy Android SDK has since been modified to make use of the device's [`ANDROID_ID`](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID) to recognize the same device between app reinstalls and reassign your app the same Pushy device token when `Pushy.register()` gets called on subsequent app reinstalls.

Similarly on iOS,  the Pushy iOS SDK persists the device credentials in the `iOS Keychain` to recognize the device between app reinstalls. The keychain persists even when your app is reinstalled multiple times.

Nothing needs to be done on your end for this to work - simply make sure you are using the latest Pushy React Native SDK and Pushy Android SDK versions and `Pushy.register()` will return the previously-assigned device token.

**Comment by leeyuejia** [comment]
Hi Thank you for your support. Yes I was using an outdated version.
