### ISSUE TITLE
Notification not working when the App is Closed in Android

### ISSUE THREAD

**Issue by robert589** [pushy-me/pushy-react-native#24]
Hi,

Right Now, when the app is closed, we cannot receive the notification.

Please note that: 
1. The app is not in battery saving mode
2. The app is not force closed, i just swipe out from the active application list.
3. the app is connected to the internet
4. I have used your TEST NOTIFICATION tool, too, and not working during the app is closed (and we able to receive when the app is opened)
My account currently has many pending notifications.

**Comment by pushy-me** [comment]
Hi @robert589,
Nice to connect with you. My name is John and I'd be glad to help you investigate this issue further.

If you could please provide the following information about the device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

Also, please consider whether the device is connecting to the Internet through a restrictive firewall which may be blocking the device from connecting to our servers.

**Comment by robert589** [comment]
We have tried to use in different device, internet, and location. so we are quite sure not because of the firewall

You can try in this phone but actually it happens in all android phone we try
1. XiaoMi
2. Redmi 5 plus (MEG7)
3. 8.1.0

**Comment by pushy-me** [comment]
Hi @robert589,
Chinese-based devices such as Huawei and Xiaomi may not receive notifications after your app is swiped away from the recent apps menu, goes to background, or after a device reboot due to custom power saving features which affect Firebase Cloud Messaging as well.

Most notably, Chinese devices from the following manufacturers include custom power-saving restrictions which may hinder background notification delivery for your app:

Xiaomi
Huawei
OnePlus
Samsung
Oppo
Vivo
Asus
Sony
Honor

Unfortunately, since these power saving mechanisms also affect FCM, it is not a Pushy-specific issue, and the only solution is to instruct the user to whitelist your app from the respective manufacturer's power saving mechanism in the Settings. The instructions for doing this vary from one manufacturer to another.

Read more about this issue:
https://dontkillmyapp.com/problem

We apologize for this inconvenience introduced by Chinese device manufacturers.

**Comment by robert589** [comment]
but we can receive other app notifications, btw, i did whitelist the app from the battery and performance setting.

Could you try the app the I have sent from the email and u try to whitelist your self?

**Comment by pushy-me** [comment]
Hi @robert589,
This behavior is most likely caused by Android's new power-saving optimizations (**Doze mode / Background Execution Limits**) which aim to conserve battery life by restricting background services for your app on Android O and newer.

Apart from the whitelisting your app from the respective Chinese manufacturer-introduced power saving optimizations, you will need to whitelist your app from the built-in Android battery optimizations to receive notifications when your app goes to background.

You can manually verify that this is indeed the cause of the issue you are experiencing by exempting your app from Android battery optimizations as follows:

Find your app in the app launcher -> tap & hold and go to App Info -> Battery -> Battery Optimization -> **Don't Optimize.**

Then, try to reproduce the behavior you have been experiencing.

To send notifications to devices with Doze / Background Execution Limits, your app can programmatically check whether it is currently exempt from battery optimizations using the `PowerManager.isIgnoringBatteryOptimizations()` API, and if not, display a dialog asking the user to exempt your app from battery optimizations if they wish to receive notifications while your app is in the background.

Please let me know if you have any questions.

**Comment by robert589** [comment]
sorry, it also does not work in IOS

**Comment by robert589** [comment]
i think we need to think why the notification only receives when we open the app. what is the scenario that this can happen.

**Comment by robert589** [comment]
I have tested using your demo https://github.com/pushy-me/pushy-demo-react-native
it is also not working when using your demo, you could investigate on that

**Comment by pushy-me** [comment]
> i think we need to think why the notification only receives when we open the app. what is the scenario that this can happen.
> 
> I also have said previously that the android has been whitelisted from battery optimization

Please read our response again regarding Android. There are two different power saving optimizations on Chinese devices that require whitelisting your app. Please follow the instructions in this comment and try again:
https://github.com/pushy-me/pushy-react-native/issues/24#issuecomment-515215073

As per iOS, maybe you are trying to send a notification to the wrong device token. What is the device token you are trying to send to?

**Comment by robert589** [comment]
OK, I just found a solution
I install this library https://github.com/stepsetgo/react-native-autostart
and put it into the App.js

        if (AutoStart.isCustomAndroid()) {
            AutoStart.startAutostartSettings();
        }

**Comment by robert589** [comment]
the problem is the app's autostart is not enabled

**Comment by pushy-me** [comment]
Hi @robert589,
This is indeed the Chinese manufacturer power saving feature we were referring to in this comment:
https://github.com/pushy-me/pushy-react-native/issues/24#issuecomment-514872317

For every manufacturer, the name is different, therefore we did not list every single name. But they all require your app to be whitelisted.
