### ISSUE TITLE
Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '4.3').

### ISSUE THREAD

**Issue by robert589** [pushy-me/pushy-react-native#28]
Hi, Pls remove the 
VERSION: 4.3 from your specfile, it causes issue in our side

**Comment by rizwankce** [comment]
If you check iOS [pushy-native-sdk](https://github.com/pushy-me/pushy-sdk-ios/blob/master/Pushy.podspec) pod file, you can see pushy only support from iOS 8.0 and swift 4.2. 

Do you have any sample project to check the issue?

**Comment by pushy-me** [comment]
Hi @robert589,
Which version of Xcode are you using?

Xcode 10 and Xcode 11 dropped support for deploying to iOS `7.0`. The earliest deployment target supported is iOS `8.0`.

**Comment by pushy-me** [comment]
Closing due to lack of response.

**Comment by pushy-me** [comment]
Hi @robert589,
Please make sure your `ios/Podfile` contains the `use_frameworks!` declaration. Newer React Native projects don't contain this declaration and throw this error.

**Find:**
```
use_native_modules!
```

**Add below:**
```
use_frameworks!
```
Save the file and close it.

Then, run the following command in your project root to reinstall the PushyRN Cocoapods dependency as a framework:

```
cd ios && pod install
```

Reopen your RN project in Xcode and see if the problem is resolved:

```
open ios/*.xcworkspace
```
