### ISSUE TITLE
No header for IOS devices

### ISSUE THREAD

**Issue by SwathyPA** [pushy-me/pushy-react-native#32]
1). When my app is killed and notification is triggered there is only a body came but no title is shown, how can I achieve that?
2). When clicking on a notification that opens the app and shows the notification again. there is no code inside my on-click notification listener

**Comment by pushy-me** [comment]
Hi @SwathyPA,
I'd be glad to assist.

1) On iOS, the expected behavior when your app has been killed (swiped away) but receives a notification, is to display that notification in the system notification bar / lock screen, with your app name as the title, which is the same behavior when your app has not been swiped away (killed).

I've just reproduced this. Can you please upload a screenshot of this strange behavior?

2) On iOS, we execute your `Pushy.setNotificationListener()` to let you know of any incoming notifications that your app received. We will call this listener as soon as we can, so if your app is open and it receives a notification, this listener will be invoked immediately. If your app was killed/backgrounded and it received a notification, the next time your app goes to foreground, the listener will be invoked.

If you don't want the alert popping up and thereby alerting the user of the notification again, simply don't invoke `Pushy.notify()` on iOS;

```
import {Platform} from 'react-native';

// Add if() around Pushy.notify() in Pushy.setNotificationListener() callback:
if (Platform.OS === 'ios') {
   Pushy.notify(notificationTitle, notificationText, data);
}
```
