### ISSUE TITLE
new install instructions please

### ISSUE THREAD

**Issue by jason-shen** [pushy-me/pushy-react-native#51]
I like what i see of pushy, but so far as a developer point of view, the docs are out of date in the latest react-native, but for now, leave me no option just have to choose another service provider that has upto date libs for implementation 

*** following the instructions on your site, is impossible to even build

**Comment by jason-shen** [comment]
remember this is  a paying service its not free.. so

**Comment by jason-shen** [comment]
this is what you get by following the instruction

[!] The 'Pods-myvcard' target has transitive dependencies that include statically linked binaries: (/Users/jasonshen/development/pushcall/myvcard/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/jasonshen/development/pushcall/myvcard/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/jasonshen/development/pushcall/myvcard/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/jasonshen/development/pushcall/myvcard/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/jasonshen/development/pushcall/myvcard/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a, and /Users/jasonshen/development/pushcall/myvcard/ios/Pods/OpenSSL-Universal/ios/lib/libssl.a)

**Comment by and-dutra** [comment]
I'm having the exact same issue https://github.com/pushy-me/pushy-react-native/issues/50

**Comment by pushy-me** [comment]
@and-dutra Thanks for your patience as we investigated this issue report further.

We've completed updating our docs and the Pushy RN SDK to support the latest versions of React Native, which have removed support for Swift dynamic frameworks.

To fix the error you are facing:
1) Install the latest version of Pushy RN by running:

```
npm install pushy-react-native@1.0.15 --save
react-native link pushy-react-native
```

2) Edit `ios/Podfile` and remove the `use_frameworks!` declaration
3) Run `pod install` to update your workspace to use static libraries instead of dynamic frameworks
4) Open the workspace in Xcod by running `open *.xcworkspace`
5) Try to build and run your project on a real device
6) Continue integration by following the instructions here:

https://pushy.me/docs/additional-platforms/react-native

Please let us know if you face any issues.

**Comment by pushy-me** [comment]
@jason-shen @and-dutra Thanks for your patience as we investigated this issue report further.

We've completed updating our docs and the Pushy RN SDK to support the latest versions of React Native, which have removed support for Swift dynamic frameworks.

To fix the error you are facing:
1) Install the latest version of Pushy RN by running:

```
npm install pushy-react-native@1.0.15 --save
react-native link pushy-react-native
```

2) Edit `ios/Podfile` and remove the `use_frameworks!` declaration
3) Run `pod install` to update your workspace to use static libraries instead of dynamic frameworks
4) Open the workspace in Xcod by running `open *.xcworkspace`
5) Try to build and run your project on a real device
6) Continue integration by following the instructions here:

https://pushy.me/docs/additional-platforms/react-native

Please let us know if you face any issues.

**Comment by causztic** [comment]
hello @pushy-me I am trying with the new instructions and I am not able to get any device token on my real device:

```typescript
    Pushy.register()
      .then(async token => {
        console.log(token)
      })
      .catch(err => {
        console.log(err)
      })
      .finally(() => console.log('here'))
```

No logs ever appeared. React Native version is 0.62.2

**Comment by pushy-me** [comment]
Hi @causztic,
Please ensure you are using an `alert()` instead of a `console.log()` as it is quite easy to miss the device token log this way:

```
// Register the user for push notifications
Pushy.register().then(async (deviceToken) => {
    // Display an alert with device token
    alert('Pushy device token: ' + deviceToken);
}).catch((err) => {
    // Handle registration errors
    console.error(err);
});
```

Run your app, and let us know if the device token appears in the alert dialog.

**Comment by causztic** [comment]
Hi, I managed to fix it by removing Firebase for now - but I require it for my authentication.
Is there any way to use both firebase and pushy at the same time?
