### ISSUE TITLE
Android Notification: Multiline text

### ISSUE THREAD

**Issue by luisfuertes** [pushy-me/pushy-react-native#69]
Im trying to show full text on android notification because the text is cut off if it is too long

With this doc
https://support.pushy.me/hc/en-us/articles/360043479192-How-can-I-customize-notifications-on-Android-

I think i should add  
```
.setStyle(new Notification.BigTextStyle().bigText(notificationText))
```

But this option is not available on pushy-react-native i think.

How can i fix it? Thanks

**Comment by pushy-me** [comment]
Hi @luisfuertes,
We'd be glad to assist. 

The built-in `Pushy.notify()` method in our React Native SDK is quite limited and does not yet support multiline notifications. To customize the notification and display long text messages without truncation, consider using a plugin called [react-native-push-notification ](https://github.com/zo0r/react-native-push-notification) instead of `Pushy.notify()`, which allows granular control of Android local notifications.

Please install and import the plugin in your `App.js` file, and replace the invocation of `Pushy.notify()` with the relevant invocation of the plugin, passing in the `bigText` parameter for multiline notification support as follows:

```
PushNotification.localNotification({
    title: "My Notification Title",
    autoCancel: true, 
    message: "My Notification Message",
    bigText: "My long message goes here", 
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    playSound: false // (optional) default: true
});

```

Please let us know if you have any questions or face any difficulties.
