### ISSUE TITLE
How to unregister from push notification in react native?

### ISSUE THREAD

**Issue by abdoutech19** [pushy-me/pushy-react-native#75]
My question is simple, how can I unregister a device token after registering it? In the documentation, it says to call `pushy.unregister(Context ctx)` for android, but I can't seem to find anything for react-native, can someone please explain how to do it I'll be really grateful?

@pushy-me

**Comment by pushy-me** [comment]
Hi @abdoutech19,
Thanks for reaching out. We'd be glad to assist.

If your intention in unregistering the device is for that device to stop receiving notifications from Pushy (and stop it from being counted as an active device in the next monthly periods), simply call `Pushy.toggleNotifications()` as follows in your RN JS code:

```
Pushy.toggleNotifications(false);
```

This will effectively prevent being billed for the device in the next billing periods, and will prevent notifications from coming in. When you'd like the device to receive notifications again, call the method again, passing in `true`:

```
Pushy.toggleNotifications(true);
```

Please let us know if this is the functionality you're looking for, and if you have any further questions.

**Comment by abdoutech19** [comment]
Hello @pushy-me,
Thanks for your response.

That partially answers my question yeah, so let's say for example I'm using a _dev_ account to register my device for push notifications and I want to unregister it from that account and move to a _production_ account, calling `Pushy.toggleNotifications(false);` will completely unregister the device from push notification associated with the _dev_ account and I can, later on, register the device in another account?

**Comment by pushy-me** [comment]
Hi @abdoutech19,
We'd be glad to clarify.

No, by calling `Pushy.toggleNotifications()` the device will retain its current device credentials and dashboard app association.

To switch the app/device over from a development Pushy dashboard app to a production Pushy app, call `Pushy.setAppId()` instead of `Pushy.toggleNotifications()` as follows:

```
Pushy.setAppId(String appId, Context ctx);
```
**Note:** The Pushy App ID can be found in the [Pushy Dashboard](https://dashboard.pushy.me/apps) -> Click your app -> App Settings -> App ID.

When you call this method with a new app ID, it will clear the stored device credentials and you will need to call `Pushy.register()` again to assign a new device token to the device, which will be tied to the Pushy App ID you pass into the `Pushy.setAppId()` method.

**Comment by abdoutech19** [comment]
Okay, that's crystal clear, thank you so much!
